package problems;

import io.reactivex.rxjava3.core.Observable;

/*
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

  1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

   1: 1
   3: 1,3
   6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
*/

public class Problem12 {

    private static int numDivisors(int x) {
        int n = 0;
        for (int i = 1; i <= Math.sqrt(x); i++) {
            if (x % i == 0) {
                n += x / i == i ? 1 : 2;
            }
        }
        return n;
    }

    public static void main(String[] args) {
        Observable<Integer> source = Observable.generate(
                () -> new int[]{0, 1},
                (state, emitter) -> {
                    state[0] += state[1]++;
                    emitter.onNext(state[0]);
                    return state;
                });

        source.filter(it -> numDivisors(it) > 500)
                .firstElement()
                .blockingSubscribe(System.out::println);
    }
}
